version: "3"
services:
  postgresql:
    image: safecast/postgresql:9.6
    environment:
      - POSTGRES_USER=safecast
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
