version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.8-node-browsers
        environment:
          RAILS_ENV: test
          AWS_DEFAULT_REGION: us-west-2
          EB_APP_NAME: ingest
      - image: mdillon/postgis:9.5
        environment:
          POSTGRES_USER: safecast
          POSTGRES_DB: safecast
          POSTGRES_PASSWORD: ""
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    steps:
      - checkout
      - run:
          name: Install build tools
          command: |
            sudo apt-get update
            sudo apt-get install -y postgresql-client python-pip
            sudo pip install awsebcli awscli
      - restore_cache:
          keys:
            - ingest-{{ checksum "Gemfile.lock" }}
            - ingest-
      - run:
          name: Bundle Install
          command: bundle install --path vendor/bundle
      - save_cache:
          key: ingest-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Wait for postgres
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Wait for elasticsearch
          command: dockerize -wait tcp://localhost:9200 -timeout 1m
      - run:
          name: Configure database
          command: cp config/database.yml.ci config/database.yml
      - run:
          name: Load schema
          command: |
            psql -h localhost -p 5432 -U safecast safecast -c 'DROP EXTENSION postgis CASCADE'
            bundle exec rake db:structure:load --trace
      - run:
          name: Run rspec
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: test_results
      - run:
          name: Create application version
          command: |
            ./.elasticbeanstalk/package.sh
